#!/usr/bin/env bash

append-path- () {
  case ":$PATH:" in
    *:"$1":*) ;;
    *)
      PATH="$1${PATH:+:$PATH}"
      export PATH
      ;;
    esac
}

# nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# rbenv
command -v rbenv >/dev/null && {
    case ":$PATH:" in
    *":$HOME/.rbenv/shims:"*) ;;
    *)
        if [[ -n "$ZSH_NAME" ]]; then
            eval "$(rbenv init - zsh)"
        elif [[ -n "$BASH" ]]; then
            eval "$(rbenv init - bash)"
        else
            eval "$(rbenv init -)"
        fi
        ;;
    esac
}

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
append-path- "$PYENV_ROOT/bin"
command -v pyenv &>/dev/null && eval "$(pyenv init -)"

# pixi
append-path- "$HOME/.pixi/bin"

# cargo
append-path- "$HOME/.cargo/bin"

# $HOME/.local/bin
append-path- "$HOME/.local/bin"

# go
append-path- "$HOME/go/bin"

# /usr/local/sbin
append-path- "/usr/local/sbin"

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
command -v sdk &>/dev/null || {
  [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
}

export CLICOLOR=1
export SYSTEMD_EDITOR="vim"
export EDITOR="vim"
export NODE_REPL_HISTORY=''
export PIPENV_VENV_IN_PROJECT=1
export POETRY_VIRTUALENVS_IN_PROJECT=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

[ -r "$HOME/.custom-shellprofile" ] && source "$HOME/.custom-shellprofile"
